// Íconos de Baraja2 — set curado de lucide-react (sin emojis en toda la app).
// Implementa BJ2-002
import {
  Heart,
  Diamond,
  Club,
  Spade,
  Sparkles,
  Flame,
  RefreshCw,
  Check,
  CircleCheck,
  X,
  ChevronLeft,
  ArrowRight,
  BellRing,
  BellOff,
  Settings,
  LogOut,
  Share2,
  Copy,
  Plane,
  Repeat,
  House,
  HeartHandshake,
  Lock,
  Swords,
  Hand,
  WifiOff,
  Crown,
  Users,
  Shuffle,
  Play,
  ShieldCheck,
  Clock,
  Mail,
  PawPrint,
  Cat,
  Dog,
  Rabbit,
  Bird,
  Fish,
  Squirrel,
  Turtle,
  Snail,
  type LucideIcon,
} from 'lucide-react';

export type { LucideIcon };

export const Icono = {
  corazon: Heart,
  corazones: HeartHandshake,
  rombo: Diamond,
  trebol: Club,
  pica: Spade,
  chispa: Sparkles,
  llama: Flame,
  recargar: RefreshCw,
  check: Check,
  cumplida: CircleCheck,
  cerrar: X,
  atras: ChevronLeft,
  flecha: ArrowRight,
  campana: BellRing,
  campanaOff: BellOff,
  ajustes: Settings,
  salir: LogOut,
  compartir: Share2,
  copiar: Copy,
  avion: Plane,
  hibrido: Repeat,
  casa: House,
  candado: Lock,
  espadas: Swords,
  mano: Hand,
  sinWifi: WifiOff,
  corona: Crown,
  pareja: Users,
  barajar: Shuffle,
  jugar: Play,
  escudo: ShieldCheck,
  reloj: Clock,
  sobre: Mail,
  huella: PawPrint,
} as const;

// Íconos-animal para los avatares provisionales (los definitivos llegan después).
export const ICONOS_ANIMAL = {
  gato: Cat,
  perro: Dog,
  conejo: Rabbit,
  ave: Bird,
  pez: Fish,
  ardilla: Squirrel,
  tortuga: Turtle,
  caracol: Snail,
} as const;

export type NombreAnimal = keyof typeof ICONOS_ANIMAL;
